# Generated by Django 2.2.3 on 2019-07-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inr_rate', models.FloatField()),
                ('usd_rate', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
