# Generated by Django 2.2.3 on 2019-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0003_auto_20190728_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecasted_INR_USD_ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inr_rate', models.FloatField()),
                ('usd_rate', models.FloatField()),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Forecasted INR_USD_RATE',
                'verbose_name_plural': 'Forecasted INR_USD_RATES',
            },
        ),
    ]
